name: progetto-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch>=2.1
      - torchvision>=0.16
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
      - Pillow
      - tensorboard
      - jsonschema
      - tqdm
